### ISSUE TITLE
Roadmap or some where to learn more about the project

### ISSUE THREAD

**Issue by tiberiusferreira** [rust-deep/deep#6]
Hello, this is quite an interesting project. I absolutely love Rust and its a shame such a high performance language has no deep learning ecosystem. 

I thought [Linfa](https://github.com/LukeMathWalker/linfa) would fill this gap, but its focus is on classical ML. 

I've been thinking about what it would take to build a good Deep Learning ecosystem in Rust, inspired by [Yolo](https://pjreddie.com/darknet/yolo/) and its Darknet raw C + Cuda implementation.

Do you guy have a roadmap? The main blocker I see is getting GPU support.

**Comment by vadixidav** [comment]
Right now most communication happens on the Discord channel (I just linked in the main group page). The main roadmap is to initially decide on an overall design for the architecture. I have a PR up (#5) to add an architecture, but we expect to change it. One everyone agrees on the architecture, we will start adding op implementations for the native backend. At some point if Rust code can build directly to GPU, we might be able to directly port those forward and backward propagation algorithms, but the framework will support the ability to create a GPU backend from day 1.

My current idea to get GPU support ASAP is to leverage the C library `arrayfire`. It will be a stopgap measure, but it will let us utilize native, CUDA, and OpenCL through a unified backend. To do that we will just create a deep-arrayfire crate that contains the arrayfire backend.

If you want to learn more, I would recommend joining the discord here: https://discord.gg/yqmFtwZ.
